### ISSUE TITLE
Any tips for using this on a matrix circuit?

### ISSUE THREAD

**Issue by geoah** [joric/bluetosis#1]
Hey there, I'm interested in getting hacking bluetosis to play nice on a [medusa](https://github.com/Gtrx0/Medusa) split that uses a matrix circuit as it supports up to a 5x7 layout.

As this is my first time playing around with keyboard code I'm wondering if you could point me to the right direction how to get this done. (I managed to flash the softdevice and precompiled bluetosis, pair it and send some keycodes from handwired keys, and I'm still trying to wrap my head around the code and how to compile it with IAR).

Any tips would be greatly appreciated.
Thank you very much for your work on bluetosis.

**Comment by realSpok** [comment]
I am working on a project like this (matrixed scan based on the bluetosis software), and I found this project to be quite helpful : 
https://github.com/Durburz/interphase-firmware?files=1. It is also based on a 5x7x2 layout, like yours and mine. 
I will post my own code once it does work. In the meantime we can exchange on the topic. 
One feature that i'm trying to achieve is to keep a couple keys hooked up on their own pin, outside the matrix so that I can still wake the keyboard up from those keys. 
I'm working on Linux so I can't help you with IAR compiling.

**Comment by joric** [comment]
Yep interphase firmware above can help. Also I really don't get the problem about compiling it with IAR. It's the easiest thing ever. Open .eww, hit compile. Also it works with GCC now so you don't need to use IAR.
